{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "from client import Client, ClientError"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [],
   "source": [
    "def run(host, port):\n",
    "    client1 = Client(host, port, timeout=5)\n",
    "    client2 = Client(host, port, timeout=5)\n",
    "    command = \"wrong command test\\n\"\n",
    "\n",
    "    print('1')\n",
    "    try:\n",
    "        data = client1.get(command)\n",
    "    except ClientError:\n",
    "        pass\n",
    "    except BaseException as err:\n",
    "        print(f\"Ошибка соединения с сервером: {err.__class__}: {err}\")\n",
    "        sys.exit(1)\n",
    "    else:\n",
    "        print(\"Неверная команда, отправленная серверу, должна возвращать ошибку протокола\")\n",
    "        sys.exit(1)\n",
    "\n",
    "    print('2')\n",
    "    command = 'some_key'\n",
    "    try:\n",
    "        data_1 = client1.get(command)\n",
    "        data_2 = client1.get(command)\n",
    "    except ClientError:\n",
    "        print('Сервер вернул ответ на валидный запрос, который клиент определил, '\n",
    "              'как не корректный.. ')\n",
    "    except BaseException as err:\n",
    "        print(f\"Сервер должен поддерживать соединение с клиентом между запросами, \"\n",
    "              f\"повторный запрос к серверу завершился ошибкой: {err.__class__}: {err}\")\n",
    "        sys.exit(1)\n",
    "\n",
    "    print('3')\n",
    "    assert data_1 == data_2 == {}, \\\n",
    "        \"На запрос клиента на получения данных по не существующему ключу, сервер \" \\\n",
    "        \"вдолжен озвращать ответ с пустым полем данных.\"\n",
    "\n",
    "    print('4')\n",
    "    try:\n",
    "        data_1 = client1.get(command)\n",
    "        data_2 = client2.get(command)\n",
    "    except ClientError:\n",
    "        print('Сервер вернул ответ на валидный запрос, который клиент определил'\n",
    "              ', как не корректный.. ')\n",
    "    except BaseException as err:\n",
    "        print(f\"Сервер должен поддерживать соединение с несколькими клиентами: \"\n",
    "              f\"{err.__class__}: {err}\")\n",
    "        sys.exit(1)\n",
    "\n",
    "    print('5')\n",
    "    assert data_1 == data_2 == {}, \\\n",
    "        \"На запрос клиента на получения данных по не существующему ключу, сервер \" \\\n",
    "        \"должен возвращать ответ с пустым полем данных.\"\n",
    "\n",
    "    print('6')\n",
    "    try:\n",
    "        client1.put(\"k1\", 0.25, timestamp=1)\n",
    "        client2.put(\"k1\", 2.156, timestamp=2)\n",
    "        client1.put(\"k1\", 0.35, timestamp=3)\n",
    "        client2.put(\"k2\", 30, timestamp=4)\n",
    "        client1.put(\"k2\", 40, timestamp=5)\n",
    "        client1.put(\"k2\", 41, timestamp=5)\n",
    "    except Exception as err:\n",
    "        print(f\"Ошибка вызова client.put(...) {err.__class__}: {err}\")\n",
    "        sys.exit(1)\n",
    "\n",
    "    print('7')\n",
    "    expected_metrics = {\n",
    "        \"k1\": [(1, 0.25), (2, 2.156), (3, 0.35)],\n",
    "        \"k2\": [(4, 30.0), (5, 41.0)],\n",
    "    }\n",
    "\n",
    "    print('8')\n",
    "    try:\n",
    "        metrics = client1.get(\"*\")\n",
    "        if metrics != expected_metrics:\n",
    "            print(f\"client.get('*') вернул неверный результат. Ожидается: \"\n",
    "                  f\"{expected_metrics}. Получено: {metrics}\")\n",
    "            sys.exit(1)\n",
    "    except Exception as err:\n",
    "        print(f\"Ошибка вызова client.get('*') {err.__class__}: {err}\")\n",
    "        sys.exit(1)\n",
    "\n",
    "    expected_metrics = {\"k2\": [(4, 30.0), (5, 41.0)]}\n",
    "\n",
    "    print('9')\n",
    "    try:\n",
    "        metrics = client2.get(\"k2\")\n",
    "        if metrics != expected_metrics:\n",
    "            print(f\"client.get('k2') вернул неверный результат. Ожидается: \"\n",
    "                  f\"{expected_metrics}. Получено: {metrics}\")\n",
    "            sys.exit(1)\n",
    "    except Exception as err:\n",
    "        print(f\"Ошибка вызова client.get('k2') {err.__class__}: {err}\")\n",
    "        sys.exit(1)\n",
    "\n",
    "    print('10')\n",
    "    try:\n",
    "        result = client1.get(\"k3\")\n",
    "        if result != {}:\n",
    "            print(\n",
    "                f\"Ошибка вызова метода get с ключом, который еще не был добавлен. \"\n",
    "                f\"Ожидается: пустой словарь. Получено: {result}\")\n",
    "            sys.exit(1)\n",
    "    except Exception as err:\n",
    "        print(f\"Ошибка вызова метода get с ключом, который еще не был добавлен: \"\n",
    "              f\"{err.__class__} {err}\")\n",
    "        sys.exit(1)\n",
    "\n",
    "    print(\"Похоже, что все верно! Попробуйте отправить решение на проверку.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1\n",
      "2\n",
      "3\n",
      "4\n",
      "5\n",
      "6\n",
      "7\n",
      "8\n",
      "9\n",
      "10\n",
      "Похоже, что все верно! Попробуйте отправить решение на проверку.\n"
     ]
    }
   ],
   "source": [
    "run(\"127.0.0.1\", 8885)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
